version: '3.9'

services:
  app:
    build:
      context: .
    container_name: images-api
    restart: unless-stopped
    ports:
      - 8080:8080
    depends_on:
      - mongo
  mongo:
    image: mongo:4.4
    container_name: images-db
    restart: always
    command: --serviceExecutor adaptive
    ports:
      - 27017:27017

